# fly.toml app configuration file generated for customer-manager-ui on 2023-05-29T20:57:57+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "customer-manager-ui"
primary_region = "waw"

[env]
REACT_APP_CUSTOMER_MANAGER_API = "http://customer-manager.internal:8080"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
